version: "3"
services:
  app:
    image: node:18
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - dynamoDb
      - initializer
  dynamoDb:
    image: amazon/dynamodb-local
  initializer:
    image: node:18
    working_dir: /code
    volumes:
      - "./others/dynamodbInitializer:/code"
    depends_on:
      - dynamoDb
